#!/bin/bash

# track current title
: ${CUSTOM_TITLE:=""}

# helper to set title
function title() {
    CUSTOM_TITLE="$*"
}

# update title in terminal
function update_title() {
    local title=$CUSTOM_TITLE
    if [[ -z $title ]]; then
        if is_worktree; then
            title="$(get_branch)"
        elif is_repo; then
            title=$(get_repo)
        else
            title=$(get_curr_dir)
        fi
    fi

    printf "\e]0;%s\7" "$title"
}
